# ..  See the NOTICE file distributed with this work for additional information
#     regarding copyright ownership.
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#       http://www.apache.org/licenses/LICENSE-2.0
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.#
#
- name: Display Env
  debug:
    var: env
- name: Create base directory
  file:
    path: "{{ base_dir }}"
    owner: "{{ remote_user_name }}"
    state: directory
    group: ensembl
    mode: '0755'
- name: Create logs directory
  file:
    path: "{{ base_dir }}/logs"
    state: directory
    owner: "{{ remote_user_name }}"
    group: ensembl
    mode: '0755'
- name: Create src directory
  file:
    path: "{{ src_dir }}"
    state: directory
    owner: "{{ remote_user_name }}"
    group: ensembl
    mode: '0755'