matrix:
  include:
    - language: java

      jdk:
        - openjdk8
      os:
        - linux

      install:
        - ./gradlew assemble

      script:
        - ./gradlew clean compileJava compileTestJava -i
        - ./gradlew search:cleanTest
        - ./gradlew search:test --tests org.ensembl.genesearch.info.*
        - ./gradlew search:test --tests org.ensembl.genesearch.output.*
        - ./gradlew search:test --tests org.ensembl.genesearch.utils.*

    - language: perl
      perl:
        - '5.14'
      services:
        - mysql
        - docker
      sudo: required
      addons:
        apt:
          packages:
            - graphviz
      before_install:
      - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
      - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-hive.git
      - git clone --branch release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git

      install:
      - cpanm --sudo -v --installdeps --notest --cpanfile ensembl-hive/cpanfile .
      - export PERL5LIB=$PERL5LIB:$PWD/bioperl-live
      - cpanm --sudo -v --installdeps --notest .
      - cpanm --sudo -n Devel::Cover::Report::Coveralls
      - cp travisci/MultiTestDB.conf.travisci  search/src/test/perl/t/MultiTestDB.conf
      - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'

      before_script:
        - docker pull docker.elastic.co/elasticsearch/elasticsearch:6.8.3
        - docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:6.8.3
        - ./search/src/main/bin/set_up_es_all.sh 127.0.0.1:9200 1

      script: ./travisci/harness.sh

notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    secure: BkrSPAkOM5aTOpeyO9vZnHdZ0LF1PLk0r2HtcXN2eTMyiHoGXkl6VUjdAL8EkzI4gunW2GProdSIjHpf60WdiEmKAulMdJRI+xyUbuxnY31mwiikS9HYwqmPBbMTf0Mh2pMBngZRFs+gaFZDUMTfLfp+8MQfU1R54yb6hPuVt5I=

