language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

install:
  - ./gradlew assemble

script:
  - ./gradlew clean compileJava compileTestJava -i -xlint
  - ./gradlew search:cleanTest search:test --tests org.ensembl.genesearch.utils.*
  - ./gradlew search:cleanTest search:test --tests org.ensembl.genesearch.info.*
  - ./gradlew search:cleanTest search:test --tests org.ensembl.genesearch.output.*
  - ./gradlew web:cleanTest web:test --tests org.ensembl.gti.genesearch.rest.MapXmlWriterTests
