language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

install:
  - ./gradlew assemble

script:
  - ./gradlew clean check -i
  - ./gradlew :search:cleanTest :search:test --tests org.ensembl.genesearch.* -ea -Dtests.security.manager=false
