language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

install:
  - ./gradlew assemble

script:
  - ./gradlew clean compileJava compileTestJava -i
  - ./gradlew search:cleanTest search:test --tests org.ensembl.genesearch.*
  # - ./gradlew web:cleanTest web:test --tests org.ensembl.gti.genesearch.rest.MapXmlWriterTest
