language: java

jdk:
  - openjdk8
os:
  - linux

install:
  - ./gradlew assemble

script:
  - ./gradlew clean compileJava compileTestJava -i
  - ./gradlew search:cleanTest
  - ./gradlew search:test --tests org.ensembl.genesearch.info.*
  - ./gradlew search:test --tests org.ensembl.genesearch.output.*
  - ./gradlew search:test --tests org.ensembl.genesearch.utils.*