version: '2.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    container_name: elastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.host=0.0.0.0"
      - network.host=0.0.0.0
      - network.publish_host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    container_name: elastic2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.8.3'
    container_name: kibana-dev
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - esnet
  elasticsearch-hq:
    image: elastichq/elasticsearch-hq
    container_name: elastic-hq-dev
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_DEBUG=False
    ports:
      - '5000:5000'
    networks:
      - esnet
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - core2:/opt/solr/server/solr/core2
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  core2:
    driver: local
networks:
  esnet:
