---
- hosts: es-data
  remote_user : "{{ remote_user }}"
  vars_files:
    - vars.yml
    - es-data-vars.yml
  roles:
    - common
    - java
    - es_core
    - es_configure
  environment:
    http_proxy: "{{ cache_proxy }}"
- hosts: es-head
  remote_user : "{{ remote_user }}"
  vars_files:
    - vars.yml
    - es-head-vars.yml
  roles:
    - common
    - java
    - es_core
    - es_configure
  environment:
    http_proxy: "{{ cache_proxy }}"
- hosts: web-head
  remote_user : "{{ remote_user }}"
  vars_files:
    - vars.yml
  roles:
    - common
    - java
    - webapp
  environment:
    http_proxy: "{{ cache_proxy }}"
