---
- hosts: es-data
  remote_user : ensprod  
  vars_files:
    - vars.yml
    - es-data-vars.yml
  roles:
    - common
    - java
    - es_core
    - es_configure
- hosts: es-head
  remote_user : ensprod  
  vars_files:
    - vars.yml
    - es-head-vars.yml
  roles:
    - common
    - java
    - es_core
    - es_configure
- hosts: web-head
  remote_user : ensprod
  vars_files:
    - vars.yml
  roles:
    - common
    - java
    - webapp
