# create a fresh config file and restart each server
---
- hosts: es-data
  remote_user : "{{ remote_user_name }}"
  vars_files:
    - vars.yml
    - es-data-vars.yml
  roles:
    - common
    - es_configure
- hosts: es-head
  remote_user : ensprod  
  vars_files:
    - vars.yml
    - es-head-vars.yml
  roles:
    - common
    - es_configure
- hosts: web-head
  remote_user : "{{ remote_user_name }}"
  vars_files:
    - vars.yml
  roles:
    - restart_web

