# ..  See the NOTICE file distributed with this work for additional information
#     regarding copyright ownership.
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#       http://www.apache.org/licenses/LICENSE-2.0
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.#
#
---
- name: Create base directory
  file:
    path: "{{ base_dir }}"
    state: directory
    recurse: yes
- name: Download Java
  local_action:
    module: command curl -L -C - -b "oraclelicense=accept-securebackup-cookie" "{{ java_url }}" -o java.tar.gz
    args:
      warn: "false"
      creates: "java.tar.gz"
- name: Create Java directory
  file:
    path: "{{ java_dir }}"
    state: directory
    recurse: yes
- name: Unpack Java
  unarchive:
    src: ./java.tar.gz
    dest: "{{ java_dir }}"
    extra_opts: ['--strip-components=1']
    creates: "{{ java_dir }}/bin/java"