---
- name: Create ES directory
  file:
    path: "{{ es_dir }}"
    state: directory
    recurse: yes
- name: Create ES logs directory
  file:
    path: "{{ base_dir }}/es_logs"
    state: directory
    recurse: yes
- name: Download and unpack Elastic
  unarchive:
    src: "{{ es_url }}"
    dest: "{{ es_dir }}"
    remote_src: yes
    extra_opts: ['--strip-components=1']
    creates: "{{ es_dir }}/bin/elasticsearch"
- name: Install control script
  template:
    src: elastic.sh.j2
    dest: "{{ es_dir }}/elastic.sh"
    mode: 0700
- name: Install head plugin
  shell: "./bin/plugin install mobz/elasticsearch-head"
  args:
    chdir: "{{ es_dir }}"
    creates: "{{ es_dir }}/plugins/head/LICENCE"
