# ..  See the NOTICE file distributed with this work for additional information
#     regarding copyright ownership.
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#       http://www.apache.org/licenses/LICENSE-2.0
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.#
#
---
- name: Create base ES directory
  file:
    path: "{{ es_dir }}"
    state: directory
    recurse: yes
- name: Create Genesearch logs directory
  file:
    path: "{{ base_dir }}/es_logs"
    state: directory
    recurse: yes
- name: Create bin directory
  file:
    path: "{{ base_dir }}/bin"
    state: directory
    recurse: yes
#- name: Remove existing
#  file:
#    state: absent
#    path: "{{ es_dir }}/*"
- name: Download ES
  local_action:
    module: command wget "{{ es_url }}" --directory-prefix={{ base_dir }}
    args:
      warn: "false"
      creates: "{{ es_archive }}"
- name: Unpack Elastic
  unarchive:
    src: "{{ base_dir }}/{{ es_archive }}"
    dest: "{{ es_dir }}"
    remote_src: yes
    extra_opts: ['--strip-components=1']
    creates: "{{ es_dir }}/bin/elasticsearch"
- name: Install control script
  template:
    src: elastic.sh.j2
    dest: "{{ base_dir }}/bin/elastic.sh"
    mode: 0700
