/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ensembl.genesearch.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Associated_xref extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Associated_xref\",\"namespace\":\"org.ensembl.genesearch.avro\",\"fields\":[{\"name\":\"experimental_evidence\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Experimental_evidence\",\"fields\":[{\"name\":\"primary_id\",\"type\":\"string\"},{\"name\":\"dbname\",\"type\":\"string\"},{\"name\":\"display_id\",\"type\":\"string\"},{\"name\":\"source\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Source\",\"fields\":[{\"name\":\"primary_id\",\"type\":\"string\"},{\"name\":\"dbname\",\"type\":\"string\"},{\"name\":\"display_id\",\"type\":\"string\"}]}}},{\"name\":\"rank\",\"type\":\"int\"}]}}},{\"name\":\"host\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Host\",\"fields\":[{\"name\":\"dbname\",\"type\":\"string\"},{\"name\":\"primary_id\",\"type\":\"string\"},{\"name\":\"rank\",\"type\":\"int\"},{\"name\":\"source\",\"type\":{\"type\":\"array\",\"items\":\"Source\"}},{\"name\":\"display_id\",\"type\":\"string\"}]}}},{\"name\":\"phenotype\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Phenotype\",\"fields\":[{\"name\":\"primary_id\",\"type\":\"string\"},{\"name\":\"dbname\",\"type\":\"string\"},{\"name\":\"source\",\"type\":{\"type\":\"array\",\"items\":\"Source\"}},{\"name\":\"rank\",\"type\":\"int\"},{\"name\":\"display_id\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<org.ensembl.genesearch.avro.Experimental_evidence> experimental_evidence;
  @Deprecated public java.util.List<org.ensembl.genesearch.avro.Host> host;
  @Deprecated public java.util.List<org.ensembl.genesearch.avro.Phenotype> phenotype;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Associated_xref() {}

  /**
   * All-args constructor.
   */
  public Associated_xref(java.util.List<org.ensembl.genesearch.avro.Experimental_evidence> experimental_evidence, java.util.List<org.ensembl.genesearch.avro.Host> host, java.util.List<org.ensembl.genesearch.avro.Phenotype> phenotype) {
    this.experimental_evidence = experimental_evidence;
    this.host = host;
    this.phenotype = phenotype;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return experimental_evidence;
    case 1: return host;
    case 2: return phenotype;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: experimental_evidence = (java.util.List<org.ensembl.genesearch.avro.Experimental_evidence>)value$; break;
    case 1: host = (java.util.List<org.ensembl.genesearch.avro.Host>)value$; break;
    case 2: phenotype = (java.util.List<org.ensembl.genesearch.avro.Phenotype>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'experimental_evidence' field.
   */
  public java.util.List<org.ensembl.genesearch.avro.Experimental_evidence> getExperimentalEvidence() {
    return experimental_evidence;
  }

  /**
   * Sets the value of the 'experimental_evidence' field.
   * @param value the value to set.
   */
  public void setExperimentalEvidence(java.util.List<org.ensembl.genesearch.avro.Experimental_evidence> value) {
    this.experimental_evidence = value;
  }

  /**
   * Gets the value of the 'host' field.
   */
  public java.util.List<org.ensembl.genesearch.avro.Host> getHost() {
    return host;
  }

  /**
   * Sets the value of the 'host' field.
   * @param value the value to set.
   */
  public void setHost(java.util.List<org.ensembl.genesearch.avro.Host> value) {
    this.host = value;
  }

  /**
   * Gets the value of the 'phenotype' field.
   */
  public java.util.List<org.ensembl.genesearch.avro.Phenotype> getPhenotype() {
    return phenotype;
  }

  /**
   * Sets the value of the 'phenotype' field.
   * @param value the value to set.
   */
  public void setPhenotype(java.util.List<org.ensembl.genesearch.avro.Phenotype> value) {
    this.phenotype = value;
  }

  /** Creates a new Associated_xref RecordBuilder */
  public static org.ensembl.genesearch.avro.Associated_xref.Builder newBuilder() {
    return new org.ensembl.genesearch.avro.Associated_xref.Builder();
  }
  
  /** Creates a new Associated_xref RecordBuilder by copying an existing Builder */
  public static org.ensembl.genesearch.avro.Associated_xref.Builder newBuilder(org.ensembl.genesearch.avro.Associated_xref.Builder other) {
    return new org.ensembl.genesearch.avro.Associated_xref.Builder(other);
  }
  
  /** Creates a new Associated_xref RecordBuilder by copying an existing Associated_xref instance */
  public static org.ensembl.genesearch.avro.Associated_xref.Builder newBuilder(org.ensembl.genesearch.avro.Associated_xref other) {
    return new org.ensembl.genesearch.avro.Associated_xref.Builder(other);
  }
  
  /**
   * RecordBuilder for Associated_xref instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Associated_xref>
    implements org.apache.avro.data.RecordBuilder<Associated_xref> {

    private java.util.List<org.ensembl.genesearch.avro.Experimental_evidence> experimental_evidence;
    private java.util.List<org.ensembl.genesearch.avro.Host> host;
    private java.util.List<org.ensembl.genesearch.avro.Phenotype> phenotype;

    /** Creates a new Builder */
    private Builder() {
      super(org.ensembl.genesearch.avro.Associated_xref.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ensembl.genesearch.avro.Associated_xref.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.experimental_evidence)) {
        this.experimental_evidence = data().deepCopy(fields()[0].schema(), other.experimental_evidence);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.host)) {
        this.host = data().deepCopy(fields()[1].schema(), other.host);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.phenotype)) {
        this.phenotype = data().deepCopy(fields()[2].schema(), other.phenotype);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Associated_xref instance */
    private Builder(org.ensembl.genesearch.avro.Associated_xref other) {
            super(org.ensembl.genesearch.avro.Associated_xref.SCHEMA$);
      if (isValidValue(fields()[0], other.experimental_evidence)) {
        this.experimental_evidence = data().deepCopy(fields()[0].schema(), other.experimental_evidence);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.host)) {
        this.host = data().deepCopy(fields()[1].schema(), other.host);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.phenotype)) {
        this.phenotype = data().deepCopy(fields()[2].schema(), other.phenotype);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'experimental_evidence' field */
    public java.util.List<org.ensembl.genesearch.avro.Experimental_evidence> getExperimentalEvidence() {
      return experimental_evidence;
    }
    
    /** Sets the value of the 'experimental_evidence' field */
    public org.ensembl.genesearch.avro.Associated_xref.Builder setExperimentalEvidence(java.util.List<org.ensembl.genesearch.avro.Experimental_evidence> value) {
      validate(fields()[0], value);
      this.experimental_evidence = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'experimental_evidence' field has been set */
    public boolean hasExperimentalEvidence() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'experimental_evidence' field */
    public org.ensembl.genesearch.avro.Associated_xref.Builder clearExperimentalEvidence() {
      experimental_evidence = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'host' field */
    public java.util.List<org.ensembl.genesearch.avro.Host> getHost() {
      return host;
    }
    
    /** Sets the value of the 'host' field */
    public org.ensembl.genesearch.avro.Associated_xref.Builder setHost(java.util.List<org.ensembl.genesearch.avro.Host> value) {
      validate(fields()[1], value);
      this.host = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'host' field has been set */
    public boolean hasHost() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'host' field */
    public org.ensembl.genesearch.avro.Associated_xref.Builder clearHost() {
      host = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'phenotype' field */
    public java.util.List<org.ensembl.genesearch.avro.Phenotype> getPhenotype() {
      return phenotype;
    }
    
    /** Sets the value of the 'phenotype' field */
    public org.ensembl.genesearch.avro.Associated_xref.Builder setPhenotype(java.util.List<org.ensembl.genesearch.avro.Phenotype> value) {
      validate(fields()[2], value);
      this.phenotype = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'phenotype' field has been set */
    public boolean hasPhenotype() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'phenotype' field */
    public org.ensembl.genesearch.avro.Associated_xref.Builder clearPhenotype() {
      phenotype = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Associated_xref build() {
      try {
        Associated_xref record = new Associated_xref();
        record.experimental_evidence = fieldSetFlags()[0] ? this.experimental_evidence : (java.util.List<org.ensembl.genesearch.avro.Experimental_evidence>) defaultValue(fields()[0]);
        record.host = fieldSetFlags()[1] ? this.host : (java.util.List<org.ensembl.genesearch.avro.Host>) defaultValue(fields()[1]);
        record.phenotype = fieldSetFlags()[2] ? this.phenotype : (java.util.List<org.ensembl.genesearch.avro.Phenotype>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
