/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ensembl.genesearch.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Host extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Host\",\"namespace\":\"org.ensembl.genesearch.avro\",\"fields\":[{\"name\":\"dbname\",\"type\":\"string\"},{\"name\":\"primary_id\",\"type\":\"string\"},{\"name\":\"rank\",\"type\":\"int\"},{\"name\":\"source\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Source\",\"fields\":[{\"name\":\"primary_id\",\"type\":\"string\"},{\"name\":\"dbname\",\"type\":\"string\"},{\"name\":\"display_id\",\"type\":\"string\"}]}}},{\"name\":\"display_id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence dbname;
  @Deprecated public java.lang.CharSequence primary_id;
  @Deprecated public int rank;
  @Deprecated public java.util.List<org.ensembl.genesearch.avro.Source> source;
  @Deprecated public java.lang.CharSequence display_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Host() {}

  /**
   * All-args constructor.
   */
  public Host(java.lang.CharSequence dbname, java.lang.CharSequence primary_id, java.lang.Integer rank, java.util.List<org.ensembl.genesearch.avro.Source> source, java.lang.CharSequence display_id) {
    this.dbname = dbname;
    this.primary_id = primary_id;
    this.rank = rank;
    this.source = source;
    this.display_id = display_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dbname;
    case 1: return primary_id;
    case 2: return rank;
    case 3: return source;
    case 4: return display_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dbname = (java.lang.CharSequence)value$; break;
    case 1: primary_id = (java.lang.CharSequence)value$; break;
    case 2: rank = (java.lang.Integer)value$; break;
    case 3: source = (java.util.List<org.ensembl.genesearch.avro.Source>)value$; break;
    case 4: display_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'dbname' field.
   */
  public java.lang.CharSequence getDbname() {
    return dbname;
  }

  /**
   * Sets the value of the 'dbname' field.
   * @param value the value to set.
   */
  public void setDbname(java.lang.CharSequence value) {
    this.dbname = value;
  }

  /**
   * Gets the value of the 'primary_id' field.
   */
  public java.lang.CharSequence getPrimaryId() {
    return primary_id;
  }

  /**
   * Sets the value of the 'primary_id' field.
   * @param value the value to set.
   */
  public void setPrimaryId(java.lang.CharSequence value) {
    this.primary_id = value;
  }

  /**
   * Gets the value of the 'rank' field.
   */
  public java.lang.Integer getRank() {
    return rank;
  }

  /**
   * Sets the value of the 'rank' field.
   * @param value the value to set.
   */
  public void setRank(java.lang.Integer value) {
    this.rank = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public java.util.List<org.ensembl.genesearch.avro.Source> getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.util.List<org.ensembl.genesearch.avro.Source> value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'display_id' field.
   */
  public java.lang.CharSequence getDisplayId() {
    return display_id;
  }

  /**
   * Sets the value of the 'display_id' field.
   * @param value the value to set.
   */
  public void setDisplayId(java.lang.CharSequence value) {
    this.display_id = value;
  }

  /** Creates a new Host RecordBuilder */
  public static org.ensembl.genesearch.avro.Host.Builder newBuilder() {
    return new org.ensembl.genesearch.avro.Host.Builder();
  }
  
  /** Creates a new Host RecordBuilder by copying an existing Builder */
  public static org.ensembl.genesearch.avro.Host.Builder newBuilder(org.ensembl.genesearch.avro.Host.Builder other) {
    return new org.ensembl.genesearch.avro.Host.Builder(other);
  }
  
  /** Creates a new Host RecordBuilder by copying an existing Host instance */
  public static org.ensembl.genesearch.avro.Host.Builder newBuilder(org.ensembl.genesearch.avro.Host other) {
    return new org.ensembl.genesearch.avro.Host.Builder(other);
  }
  
  /**
   * RecordBuilder for Host instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Host>
    implements org.apache.avro.data.RecordBuilder<Host> {

    private java.lang.CharSequence dbname;
    private java.lang.CharSequence primary_id;
    private int rank;
    private java.util.List<org.ensembl.genesearch.avro.Source> source;
    private java.lang.CharSequence display_id;

    /** Creates a new Builder */
    private Builder() {
      super(org.ensembl.genesearch.avro.Host.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ensembl.genesearch.avro.Host.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.dbname)) {
        this.dbname = data().deepCopy(fields()[0].schema(), other.dbname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.primary_id)) {
        this.primary_id = data().deepCopy(fields()[1].schema(), other.primary_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rank)) {
        this.rank = data().deepCopy(fields()[2].schema(), other.rank);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.source)) {
        this.source = data().deepCopy(fields()[3].schema(), other.source);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.display_id)) {
        this.display_id = data().deepCopy(fields()[4].schema(), other.display_id);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Host instance */
    private Builder(org.ensembl.genesearch.avro.Host other) {
            super(org.ensembl.genesearch.avro.Host.SCHEMA$);
      if (isValidValue(fields()[0], other.dbname)) {
        this.dbname = data().deepCopy(fields()[0].schema(), other.dbname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.primary_id)) {
        this.primary_id = data().deepCopy(fields()[1].schema(), other.primary_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rank)) {
        this.rank = data().deepCopy(fields()[2].schema(), other.rank);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.source)) {
        this.source = data().deepCopy(fields()[3].schema(), other.source);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.display_id)) {
        this.display_id = data().deepCopy(fields()[4].schema(), other.display_id);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'dbname' field */
    public java.lang.CharSequence getDbname() {
      return dbname;
    }
    
    /** Sets the value of the 'dbname' field */
    public org.ensembl.genesearch.avro.Host.Builder setDbname(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.dbname = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'dbname' field has been set */
    public boolean hasDbname() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'dbname' field */
    public org.ensembl.genesearch.avro.Host.Builder clearDbname() {
      dbname = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'primary_id' field */
    public java.lang.CharSequence getPrimaryId() {
      return primary_id;
    }
    
    /** Sets the value of the 'primary_id' field */
    public org.ensembl.genesearch.avro.Host.Builder setPrimaryId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.primary_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'primary_id' field has been set */
    public boolean hasPrimaryId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'primary_id' field */
    public org.ensembl.genesearch.avro.Host.Builder clearPrimaryId() {
      primary_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'rank' field */
    public java.lang.Integer getRank() {
      return rank;
    }
    
    /** Sets the value of the 'rank' field */
    public org.ensembl.genesearch.avro.Host.Builder setRank(int value) {
      validate(fields()[2], value);
      this.rank = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'rank' field has been set */
    public boolean hasRank() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'rank' field */
    public org.ensembl.genesearch.avro.Host.Builder clearRank() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'source' field */
    public java.util.List<org.ensembl.genesearch.avro.Source> getSource() {
      return source;
    }
    
    /** Sets the value of the 'source' field */
    public org.ensembl.genesearch.avro.Host.Builder setSource(java.util.List<org.ensembl.genesearch.avro.Source> value) {
      validate(fields()[3], value);
      this.source = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'source' field has been set */
    public boolean hasSource() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'source' field */
    public org.ensembl.genesearch.avro.Host.Builder clearSource() {
      source = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'display_id' field */
    public java.lang.CharSequence getDisplayId() {
      return display_id;
    }
    
    /** Sets the value of the 'display_id' field */
    public org.ensembl.genesearch.avro.Host.Builder setDisplayId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.display_id = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'display_id' field has been set */
    public boolean hasDisplayId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'display_id' field */
    public org.ensembl.genesearch.avro.Host.Builder clearDisplayId() {
      display_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Host build() {
      try {
        Host record = new Host();
        record.dbname = fieldSetFlags()[0] ? this.dbname : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.primary_id = fieldSetFlags()[1] ? this.primary_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.rank = fieldSetFlags()[2] ? this.rank : (java.lang.Integer) defaultValue(fields()[2]);
        record.source = fieldSetFlags()[3] ? this.source : (java.util.List<org.ensembl.genesearch.avro.Source>) defaultValue(fields()[3]);
        record.display_id = fieldSetFlags()[4] ? this.display_id : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
