/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ensembl.genesearch.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Source extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Source\",\"namespace\":\"org.ensembl.genesearch.avro\",\"fields\":[{\"name\":\"primary_id\",\"type\":\"string\"},{\"name\":\"dbname\",\"type\":\"string\"},{\"name\":\"display_id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence primary_id;
  @Deprecated public java.lang.CharSequence dbname;
  @Deprecated public java.lang.CharSequence display_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Source() {}

  /**
   * All-args constructor.
   */
  public Source(java.lang.CharSequence primary_id, java.lang.CharSequence dbname, java.lang.CharSequence display_id) {
    this.primary_id = primary_id;
    this.dbname = dbname;
    this.display_id = display_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return primary_id;
    case 1: return dbname;
    case 2: return display_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: primary_id = (java.lang.CharSequence)value$; break;
    case 1: dbname = (java.lang.CharSequence)value$; break;
    case 2: display_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'primary_id' field.
   */
  public java.lang.CharSequence getPrimaryId() {
    return primary_id;
  }

  /**
   * Sets the value of the 'primary_id' field.
   * @param value the value to set.
   */
  public void setPrimaryId(java.lang.CharSequence value) {
    this.primary_id = value;
  }

  /**
   * Gets the value of the 'dbname' field.
   */
  public java.lang.CharSequence getDbname() {
    return dbname;
  }

  /**
   * Sets the value of the 'dbname' field.
   * @param value the value to set.
   */
  public void setDbname(java.lang.CharSequence value) {
    this.dbname = value;
  }

  /**
   * Gets the value of the 'display_id' field.
   */
  public java.lang.CharSequence getDisplayId() {
    return display_id;
  }

  /**
   * Sets the value of the 'display_id' field.
   * @param value the value to set.
   */
  public void setDisplayId(java.lang.CharSequence value) {
    this.display_id = value;
  }

  /** Creates a new Source RecordBuilder */
  public static org.ensembl.genesearch.avro.Source.Builder newBuilder() {
    return new org.ensembl.genesearch.avro.Source.Builder();
  }
  
  /** Creates a new Source RecordBuilder by copying an existing Builder */
  public static org.ensembl.genesearch.avro.Source.Builder newBuilder(org.ensembl.genesearch.avro.Source.Builder other) {
    return new org.ensembl.genesearch.avro.Source.Builder(other);
  }
  
  /** Creates a new Source RecordBuilder by copying an existing Source instance */
  public static org.ensembl.genesearch.avro.Source.Builder newBuilder(org.ensembl.genesearch.avro.Source other) {
    return new org.ensembl.genesearch.avro.Source.Builder(other);
  }
  
  /**
   * RecordBuilder for Source instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Source>
    implements org.apache.avro.data.RecordBuilder<Source> {

    private java.lang.CharSequence primary_id;
    private java.lang.CharSequence dbname;
    private java.lang.CharSequence display_id;

    /** Creates a new Builder */
    private Builder() {
      super(org.ensembl.genesearch.avro.Source.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ensembl.genesearch.avro.Source.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.primary_id)) {
        this.primary_id = data().deepCopy(fields()[0].schema(), other.primary_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dbname)) {
        this.dbname = data().deepCopy(fields()[1].schema(), other.dbname);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.display_id)) {
        this.display_id = data().deepCopy(fields()[2].schema(), other.display_id);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Source instance */
    private Builder(org.ensembl.genesearch.avro.Source other) {
            super(org.ensembl.genesearch.avro.Source.SCHEMA$);
      if (isValidValue(fields()[0], other.primary_id)) {
        this.primary_id = data().deepCopy(fields()[0].schema(), other.primary_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dbname)) {
        this.dbname = data().deepCopy(fields()[1].schema(), other.dbname);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.display_id)) {
        this.display_id = data().deepCopy(fields()[2].schema(), other.display_id);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'primary_id' field */
    public java.lang.CharSequence getPrimaryId() {
      return primary_id;
    }
    
    /** Sets the value of the 'primary_id' field */
    public org.ensembl.genesearch.avro.Source.Builder setPrimaryId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.primary_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'primary_id' field has been set */
    public boolean hasPrimaryId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'primary_id' field */
    public org.ensembl.genesearch.avro.Source.Builder clearPrimaryId() {
      primary_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'dbname' field */
    public java.lang.CharSequence getDbname() {
      return dbname;
    }
    
    /** Sets the value of the 'dbname' field */
    public org.ensembl.genesearch.avro.Source.Builder setDbname(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.dbname = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'dbname' field has been set */
    public boolean hasDbname() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'dbname' field */
    public org.ensembl.genesearch.avro.Source.Builder clearDbname() {
      dbname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'display_id' field */
    public java.lang.CharSequence getDisplayId() {
      return display_id;
    }
    
    /** Sets the value of the 'display_id' field */
    public org.ensembl.genesearch.avro.Source.Builder setDisplayId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.display_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'display_id' field has been set */
    public boolean hasDisplayId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'display_id' field */
    public org.ensembl.genesearch.avro.Source.Builder clearDisplayId() {
      display_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Source build() {
      try {
        Source record = new Source();
        record.primary_id = fieldSetFlags()[0] ? this.primary_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.dbname = fieldSetFlags()[1] ? this.dbname : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.display_id = fieldSetFlags()[2] ? this.display_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
